services:
  worker:
    image: worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - ./shared:/app/shared
    entrypoint: [ "/bin/bash", "-c", "tail -f /dev/null" ]
